// Autogenerated from Pigeon (v28.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package io.github.wreos.microsoft_entra_external_id

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
private object NativeAuthApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

enum class NativePlatformMessage(val raw: Int) {
  ANDROID(0),
  IOS(1);

  companion object {
    fun ofRaw(raw: Int): NativePlatformMessage? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class NativeAuthOperationMessage(val raw: Int) {
  SIGN_IN(0),
  SIGN_UP(1);

  companion object {
    fun ofRaw(raw: Int): NativeAuthOperationMessage? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class NativeAuthResultTypeMessage(val raw: Int) {
  INITIALIZED(0),
  SIGNED_OUT(1),
  CODE_REQUIRED(2),
  PASSWORD_REQUIRED(3),
  SIGNED_IN(4),
  ERROR(5),
  BROWSER_REQUIRED(6);

  companion object {
    fun ofRaw(raw: Int): NativeAuthResultTypeMessage? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeSdkStatusMessage (
  val platform: NativePlatformMessage,
  val linked: Boolean,
  val sdkVersion: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeSdkStatusMessage {
      val platform = pigeonVar_list[0] as NativePlatformMessage
      val linked = pigeonVar_list[1] as Boolean
      val sdkVersion = pigeonVar_list[2] as String?
      return NativeSdkStatusMessage(platform, linked, sdkVersion)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      platform,
      linked,
      sdkVersion,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeSdkStatusMessage
    return NativeAuthApiPigeonUtils.deepEquals(this.platform, other.platform) && NativeAuthApiPigeonUtils.deepEquals(this.linked, other.linked) && NativeAuthApiPigeonUtils.deepEquals(this.sdkVersion, other.sdkVersion)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + NativeAuthApiPigeonUtils.deepHash(this.platform)
    result = 31 * result + NativeAuthApiPigeonUtils.deepHash(this.linked)
    result = 31 * result + NativeAuthApiPigeonUtils.deepHash(this.sdkVersion)
    return result
  }
  override fun toString(): String {
    return "NativeSdkStatusMessage(platform=$platform, linked=$linked, sdkVersion=$sdkVersion)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeAuthConfigurationMessage (
  val clientId: String,
  val tenantSubdomain: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeAuthConfigurationMessage {
      val clientId = pigeonVar_list[0] as String
      val tenantSubdomain = pigeonVar_list[1] as String
      return NativeAuthConfigurationMessage(clientId, tenantSubdomain)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      clientId,
      tenantSubdomain,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeAuthConfigurationMessage
    return NativeAuthApiPigeonUtils.deepEquals(this.clientId, other.clientId) && NativeAuthApiPigeonUtils.deepEquals(this.tenantSubdomain, other.tenantSubdomain)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + NativeAuthApiPigeonUtils.deepHash(this.clientId)
    result = 31 * result + NativeAuthApiPigeonUtils.deepHash(this.tenantSubdomain)
    return result
  }
  override fun toString(): String {
    return "NativeAuthConfigurationMessage(clientId=$clientId, tenantSubdomain=$tenantSubdomain)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeAuthSignInParametersMessage (
  val username: String,
  val password: String? = null,
  val scopes: List<String>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeAuthSignInParametersMessage {
      val username = pigeonVar_list[0] as String
      val password = pigeonVar_list[1] as String?
      val scopes = pigeonVar_list[2] as List<String>
      return NativeAuthSignInParametersMessage(username, password, scopes)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      username,
      password,
      scopes,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeAuthSignInParametersMessage
    return NativeAuthApiPigeonUtils.deepEquals(this.username, other.username) && NativeAuthApiPigeonUtils.deepEquals(this.password, other.password) && NativeAuthApiPigeonUtils.deepEquals(this.scopes, other.scopes)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + NativeAuthApiPigeonUtils.deepHash(this.username)
    result = 31 * result + NativeAuthApiPigeonUtils.deepHash(this.password)
    result = 31 * result + NativeAuthApiPigeonUtils.deepHash(this.scopes)
    return result
  }
  override fun toString(): String {
    return "NativeAuthSignInParametersMessage(username=$username, password=$password, scopes=$scopes)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeAuthAccessTokenParametersMessage (
  val scopes: List<String>,
  val forceRefresh: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeAuthAccessTokenParametersMessage {
      val scopes = pigeonVar_list[0] as List<String>
      val forceRefresh = pigeonVar_list[1] as Boolean
      return NativeAuthAccessTokenParametersMessage(scopes, forceRefresh)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      scopes,
      forceRefresh,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeAuthAccessTokenParametersMessage
    return NativeAuthApiPigeonUtils.deepEquals(this.scopes, other.scopes) && NativeAuthApiPigeonUtils.deepEquals(this.forceRefresh, other.forceRefresh)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + NativeAuthApiPigeonUtils.deepHash(this.scopes)
    result = 31 * result + NativeAuthApiPigeonUtils.deepHash(this.forceRefresh)
    return result
  }
  override fun toString(): String {
    return "NativeAuthAccessTokenParametersMessage(scopes=$scopes, forceRefresh=$forceRefresh)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeAuthResultMessage (
  val type: NativeAuthResultTypeMessage,
  val operation: NativeAuthOperationMessage? = null,
  val continuationId: String? = null,
  val username: String? = null,
  val idToken: String? = null,
  val accessToken: String? = null,
  val scopes: List<String>? = null,
  val expiresAtEpochMilliseconds: Long? = null,
  val sentTo: String? = null,
  val codeLength: Long? = null,
  val errorCode: String? = null,
  val errorMessage: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeAuthResultMessage {
      val type = pigeonVar_list[0] as NativeAuthResultTypeMessage
      val operation = pigeonVar_list[1] as NativeAuthOperationMessage?
      val continuationId = pigeonVar_list[2] as String?
      val username = pigeonVar_list[3] as String?
      val idToken = pigeonVar_list[4] as String?
      val accessToken = pigeonVar_list[5] as String?
      val scopes = pigeonVar_list[6] as List<String>?
      val expiresAtEpochMilliseconds = pigeonVar_list[7] as Long?
      val sentTo = pigeonVar_list[8] as String?
      val codeLength = pigeonVar_list[9] as Long?
      val errorCode = pigeonVar_list[10] as String?
      val errorMessage = pigeonVar_list[11] as String?
      return NativeAuthResultMessage(type, operation, continuationId, username, idToken, accessToken, scopes, expiresAtEpochMilliseconds, sentTo, codeLength, errorCode, errorMessage)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      type,
      operation,
      continuationId,
      username,
      idToken,
      accessToken,
      scopes,
      expiresAtEpochMilliseconds,
      sentTo,
      codeLength,
      errorCode,
      errorMessage,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeAuthResultMessage
    return NativeAuthApiPigeonUtils.deepEquals(this.type, other.type) && NativeAuthApiPigeonUtils.deepEquals(this.operation, other.operation) && NativeAuthApiPigeonUtils.deepEquals(this.continuationId, other.continuationId) && NativeAuthApiPigeonUtils.deepEquals(this.username, other.username) && NativeAuthApiPigeonUtils.deepEquals(this.idToken, other.idToken) && NativeAuthApiPigeonUtils.deepEquals(this.accessToken, other.accessToken) && NativeAuthApiPigeonUtils.deepEquals(this.scopes, other.scopes) && NativeAuthApiPigeonUtils.deepEquals(this.expiresAtEpochMilliseconds, other.expiresAtEpochMilliseconds) && NativeAuthApiPigeonUtils.deepEquals(this.sentTo, other.sentTo) && NativeAuthApiPigeonUtils.deepEquals(this.codeLength, other.codeLength) && NativeAuthApiPigeonUtils.deepEquals(this.errorCode, other.errorCode) && NativeAuthApiPigeonUtils.deepEquals(this.errorMessage, other.errorMessage)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + NativeAuthApiPigeonUtils.deepHash(this.type)
    result = 31 * result + NativeAuthApiPigeonUtils.deepHash(this.operation)
    result = 31 * result + NativeAuthApiPigeonUtils.deepHash(this.continuationId)
    result = 31 * result + NativeAuthApiPigeonUtils.deepHash(this.username)
    result = 31 * result + NativeAuthApiPigeonUtils.deepHash(this.idToken)
    result = 31 * result + NativeAuthApiPigeonUtils.deepHash(this.accessToken)
    result = 31 * result + NativeAuthApiPigeonUtils.deepHash(this.scopes)
    result = 31 * result + NativeAuthApiPigeonUtils.deepHash(this.expiresAtEpochMilliseconds)
    result = 31 * result + NativeAuthApiPigeonUtils.deepHash(this.sentTo)
    result = 31 * result + NativeAuthApiPigeonUtils.deepHash(this.codeLength)
    result = 31 * result + NativeAuthApiPigeonUtils.deepHash(this.errorCode)
    result = 31 * result + NativeAuthApiPigeonUtils.deepHash(this.errorMessage)
    return result
  }
  override fun toString(): String {
    return "NativeAuthResultMessage(type=$type, operation=$operation, continuationId=$continuationId, username=$username, idToken=$idToken, accessToken=$accessToken, scopes=$scopes, expiresAtEpochMilliseconds=$expiresAtEpochMilliseconds, sentTo=$sentTo, codeLength=$codeLength, errorCode=$errorCode, errorMessage=$errorMessage)"
  }
}
private open class NativeAuthApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          NativePlatformMessage.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          NativeAuthOperationMessage.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          NativeAuthResultTypeMessage.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeSdkStatusMessage.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeAuthConfigurationMessage.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeAuthSignInParametersMessage.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeAuthAccessTokenParametersMessage.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeAuthResultMessage.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is NativePlatformMessage -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is NativeAuthOperationMessage -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is NativeAuthResultTypeMessage -> {
        stream.write(131)
        writeValue(stream, value.raw.toLong())
      }
      is NativeSdkStatusMessage -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is NativeAuthConfigurationMessage -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is NativeAuthSignInParametersMessage -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is NativeAuthAccessTokenParametersMessage -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is NativeAuthResultMessage -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface NativeAuthHostApi {
  fun getNativeSdkStatus(): NativeSdkStatusMessage
  suspend fun initialize(configuration: NativeAuthConfigurationMessage): NativeAuthResultMessage
  suspend fun getCurrentAccount(): NativeAuthResultMessage
  suspend fun startSignIn(parameters: NativeAuthSignInParametersMessage): NativeAuthResultMessage
  suspend fun startSignUp(username: String): NativeAuthResultMessage
  suspend fun submitCode(continuationId: String, code: String): NativeAuthResultMessage
  suspend fun submitPassword(continuationId: String, password: String): NativeAuthResultMessage
  suspend fun resendCode(continuationId: String): NativeAuthResultMessage
  suspend fun getAccessToken(parameters: NativeAuthAccessTokenParametersMessage): NativeAuthResultMessage
  suspend fun signOut(): NativeAuthResultMessage

  companion object {
    /** The codec used by NativeAuthHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      NativeAuthApiPigeonCodec()
    }
    /** Sets up an instance of `NativeAuthHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: NativeAuthHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.microsoft_entra_external_id.NativeAuthHostApi.getNativeSdkStatus$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getNativeSdkStatus())
            } catch (exception: Throwable) {
              NativeAuthApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.microsoft_entra_external_id.NativeAuthHostApi.initialize$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val configurationArg = args[0] as NativeAuthConfigurationMessage
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.initialize(configurationArg))
              } catch (exception: Throwable) {
                NativeAuthApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.microsoft_entra_external_id.NativeAuthHostApi.getCurrentAccount$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.getCurrentAccount())
              } catch (exception: Throwable) {
                NativeAuthApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.microsoft_entra_external_id.NativeAuthHostApi.startSignIn$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val parametersArg = args[0] as NativeAuthSignInParametersMessage
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.startSignIn(parametersArg))
              } catch (exception: Throwable) {
                NativeAuthApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.microsoft_entra_external_id.NativeAuthHostApi.startSignUp$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val usernameArg = args[0] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.startSignUp(usernameArg))
              } catch (exception: Throwable) {
                NativeAuthApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.microsoft_entra_external_id.NativeAuthHostApi.submitCode$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val continuationIdArg = args[0] as String
            val codeArg = args[1] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.submitCode(continuationIdArg, codeArg))
              } catch (exception: Throwable) {
                NativeAuthApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.microsoft_entra_external_id.NativeAuthHostApi.submitPassword$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val continuationIdArg = args[0] as String
            val passwordArg = args[1] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.submitPassword(continuationIdArg, passwordArg))
              } catch (exception: Throwable) {
                NativeAuthApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.microsoft_entra_external_id.NativeAuthHostApi.resendCode$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val continuationIdArg = args[0] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.resendCode(continuationIdArg))
              } catch (exception: Throwable) {
                NativeAuthApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.microsoft_entra_external_id.NativeAuthHostApi.getAccessToken$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val parametersArg = args[0] as NativeAuthAccessTokenParametersMessage
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.getAccessToken(parametersArg))
              } catch (exception: Throwable) {
                NativeAuthApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.microsoft_entra_external_id.NativeAuthHostApi.signOut$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.signOut())
              } catch (exception: Throwable) {
                NativeAuthApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
