version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '04:00'
      timezone: Europe/Berlin
    labels:
      - dependencies
      - ci
    groups:
      github-actions:
        patterns:
          - '*'

  - package-ecosystem: pub
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '04:15'
      timezone: Europe/Berlin
    labels:
      - dependencies
      - dart

  - package-ecosystem: pub
    directory: /example
    schedule:
      interval: weekly
      day: monday
      time: '04:30'
      timezone: Europe/Berlin
    labels:
      - dependencies
      - dart

  - package-ecosystem: gradle
    directory: /example/android
    schedule:
      interval: weekly
      day: monday
      time: '04:45'
      timezone: Europe/Berlin
    labels:
      - dependencies
      - android
    groups:
      android-toolchain:
        patterns:
          - '*'

  - package-ecosystem: swift
    directory: /ios/entra_external_id
    schedule:
      interval: weekly
      day: monday
      time: '05:00'
      timezone: Europe/Berlin
    labels:
      - dependencies
      - ios
