// Autogenerated from Pigeon (v28.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum NativeAuthApiPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


enum NativePlatformMessage: Int, CaseIterable {
  case android = 0
  case ios = 1
}

enum NativeAuthOperationMessage: Int, CaseIterable {
  case signIn = 0
  case signUp = 1
}

enum NativeAuthResultTypeMessage: Int, CaseIterable {
  case initialized = 0
  case signedOut = 1
  case codeRequired = 2
  case passwordRequired = 3
  case signedIn = 4
  case error = 5
  case browserRequired = 6
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeSdkStatusMessage: Hashable, CustomStringConvertible {
  var platform: NativePlatformMessage
  var linked: Bool
  var sdkVersion: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeSdkStatusMessage? {
    let platform = pigeonVar_list[0] as! NativePlatformMessage
    let linked = pigeonVar_list[1] as! Bool
    let sdkVersion: String? = nilOrValue(pigeonVar_list[2])

    return NativeSdkStatusMessage(
      platform: platform,
      linked: linked,
      sdkVersion: sdkVersion
    )
  }
  func toList() -> [Any?] {
    return [
      platform,
      linked,
      sdkVersion,
    ]
  }
  static func == (lhs: NativeSdkStatusMessage, rhs: NativeSdkStatusMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return NativeAuthApiPigeonInternal.deepEquals(lhs.platform, rhs.platform) && NativeAuthApiPigeonInternal.deepEquals(lhs.linked, rhs.linked) && NativeAuthApiPigeonInternal.deepEquals(lhs.sdkVersion, rhs.sdkVersion)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeSdkStatusMessage")
    NativeAuthApiPigeonInternal.deepHash(value: platform, hasher: &hasher)
    NativeAuthApiPigeonInternal.deepHash(value: linked, hasher: &hasher)
    NativeAuthApiPigeonInternal.deepHash(value: sdkVersion, hasher: &hasher)
  }

  public var description: String {
    return "NativeSdkStatusMessage(platform: \(String(describing: platform)), linked: \(String(describing: linked)), sdkVersion: \(String(describing: sdkVersion)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeAuthConfigurationMessage: Hashable, CustomStringConvertible {
  var clientId: String
  var tenantSubdomain: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeAuthConfigurationMessage? {
    let clientId = pigeonVar_list[0] as! String
    let tenantSubdomain = pigeonVar_list[1] as! String

    return NativeAuthConfigurationMessage(
      clientId: clientId,
      tenantSubdomain: tenantSubdomain
    )
  }
  func toList() -> [Any?] {
    return [
      clientId,
      tenantSubdomain,
    ]
  }
  static func == (lhs: NativeAuthConfigurationMessage, rhs: NativeAuthConfigurationMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return NativeAuthApiPigeonInternal.deepEquals(lhs.clientId, rhs.clientId) && NativeAuthApiPigeonInternal.deepEquals(lhs.tenantSubdomain, rhs.tenantSubdomain)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeAuthConfigurationMessage")
    NativeAuthApiPigeonInternal.deepHash(value: clientId, hasher: &hasher)
    NativeAuthApiPigeonInternal.deepHash(value: tenantSubdomain, hasher: &hasher)
  }

  public var description: String {
    return "NativeAuthConfigurationMessage(clientId: \(String(describing: clientId)), tenantSubdomain: \(String(describing: tenantSubdomain)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeAuthSignInParametersMessage: Hashable, CustomStringConvertible {
  var username: String
  var password: String? = nil
  var scopes: [String]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeAuthSignInParametersMessage? {
    let username = pigeonVar_list[0] as! String
    let password: String? = nilOrValue(pigeonVar_list[1])
    let scopes = pigeonVar_list[2] as! [String]

    return NativeAuthSignInParametersMessage(
      username: username,
      password: password,
      scopes: scopes
    )
  }
  func toList() -> [Any?] {
    return [
      username,
      password,
      scopes,
    ]
  }
  static func == (lhs: NativeAuthSignInParametersMessage, rhs: NativeAuthSignInParametersMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return NativeAuthApiPigeonInternal.deepEquals(lhs.username, rhs.username) && NativeAuthApiPigeonInternal.deepEquals(lhs.password, rhs.password) && NativeAuthApiPigeonInternal.deepEquals(lhs.scopes, rhs.scopes)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeAuthSignInParametersMessage")
    NativeAuthApiPigeonInternal.deepHash(value: username, hasher: &hasher)
    NativeAuthApiPigeonInternal.deepHash(value: password, hasher: &hasher)
    NativeAuthApiPigeonInternal.deepHash(value: scopes, hasher: &hasher)
  }

  public var description: String {
    return "NativeAuthSignInParametersMessage(username: \(String(describing: username)), password: \(String(describing: password)), scopes: \(String(describing: scopes)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeAuthAccessTokenParametersMessage: Hashable, CustomStringConvertible {
  var scopes: [String]
  var forceRefresh: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeAuthAccessTokenParametersMessage? {
    let scopes = pigeonVar_list[0] as! [String]
    let forceRefresh = pigeonVar_list[1] as! Bool

    return NativeAuthAccessTokenParametersMessage(
      scopes: scopes,
      forceRefresh: forceRefresh
    )
  }
  func toList() -> [Any?] {
    return [
      scopes,
      forceRefresh,
    ]
  }
  static func == (lhs: NativeAuthAccessTokenParametersMessage, rhs: NativeAuthAccessTokenParametersMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return NativeAuthApiPigeonInternal.deepEquals(lhs.scopes, rhs.scopes) && NativeAuthApiPigeonInternal.deepEquals(lhs.forceRefresh, rhs.forceRefresh)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeAuthAccessTokenParametersMessage")
    NativeAuthApiPigeonInternal.deepHash(value: scopes, hasher: &hasher)
    NativeAuthApiPigeonInternal.deepHash(value: forceRefresh, hasher: &hasher)
  }

  public var description: String {
    return "NativeAuthAccessTokenParametersMessage(scopes: \(String(describing: scopes)), forceRefresh: \(String(describing: forceRefresh)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeAuthResultMessage: Hashable, CustomStringConvertible {
  var type: NativeAuthResultTypeMessage
  var operation: NativeAuthOperationMessage? = nil
  var continuationId: String? = nil
  var username: String? = nil
  var idToken: String? = nil
  var accessToken: String? = nil
  var scopes: [String]? = nil
  var expiresAtEpochMilliseconds: Int64? = nil
  var sentTo: String? = nil
  var codeLength: Int64? = nil
  var errorCode: String? = nil
  var errorMessage: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeAuthResultMessage? {
    let type = pigeonVar_list[0] as! NativeAuthResultTypeMessage
    let operation: NativeAuthOperationMessage? = nilOrValue(pigeonVar_list[1])
    let continuationId: String? = nilOrValue(pigeonVar_list[2])
    let username: String? = nilOrValue(pigeonVar_list[3])
    let idToken: String? = nilOrValue(pigeonVar_list[4])
    let accessToken: String? = nilOrValue(pigeonVar_list[5])
    let scopes: [String]? = nilOrValue(pigeonVar_list[6])
    let expiresAtEpochMilliseconds: Int64? = nilOrValue(pigeonVar_list[7])
    let sentTo: String? = nilOrValue(pigeonVar_list[8])
    let codeLength: Int64? = nilOrValue(pigeonVar_list[9])
    let errorCode: String? = nilOrValue(pigeonVar_list[10])
    let errorMessage: String? = nilOrValue(pigeonVar_list[11])

    return NativeAuthResultMessage(
      type: type,
      operation: operation,
      continuationId: continuationId,
      username: username,
      idToken: idToken,
      accessToken: accessToken,
      scopes: scopes,
      expiresAtEpochMilliseconds: expiresAtEpochMilliseconds,
      sentTo: sentTo,
      codeLength: codeLength,
      errorCode: errorCode,
      errorMessage: errorMessage
    )
  }
  func toList() -> [Any?] {
    return [
      type,
      operation,
      continuationId,
      username,
      idToken,
      accessToken,
      scopes,
      expiresAtEpochMilliseconds,
      sentTo,
      codeLength,
      errorCode,
      errorMessage,
    ]
  }
  static func == (lhs: NativeAuthResultMessage, rhs: NativeAuthResultMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return NativeAuthApiPigeonInternal.deepEquals(lhs.type, rhs.type) && NativeAuthApiPigeonInternal.deepEquals(lhs.operation, rhs.operation) && NativeAuthApiPigeonInternal.deepEquals(lhs.continuationId, rhs.continuationId) && NativeAuthApiPigeonInternal.deepEquals(lhs.username, rhs.username) && NativeAuthApiPigeonInternal.deepEquals(lhs.idToken, rhs.idToken) && NativeAuthApiPigeonInternal.deepEquals(lhs.accessToken, rhs.accessToken) && NativeAuthApiPigeonInternal.deepEquals(lhs.scopes, rhs.scopes) && NativeAuthApiPigeonInternal.deepEquals(lhs.expiresAtEpochMilliseconds, rhs.expiresAtEpochMilliseconds) && NativeAuthApiPigeonInternal.deepEquals(lhs.sentTo, rhs.sentTo) && NativeAuthApiPigeonInternal.deepEquals(lhs.codeLength, rhs.codeLength) && NativeAuthApiPigeonInternal.deepEquals(lhs.errorCode, rhs.errorCode) && NativeAuthApiPigeonInternal.deepEquals(lhs.errorMessage, rhs.errorMessage)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeAuthResultMessage")
    NativeAuthApiPigeonInternal.deepHash(value: type, hasher: &hasher)
    NativeAuthApiPigeonInternal.deepHash(value: operation, hasher: &hasher)
    NativeAuthApiPigeonInternal.deepHash(value: continuationId, hasher: &hasher)
    NativeAuthApiPigeonInternal.deepHash(value: username, hasher: &hasher)
    NativeAuthApiPigeonInternal.deepHash(value: idToken, hasher: &hasher)
    NativeAuthApiPigeonInternal.deepHash(value: accessToken, hasher: &hasher)
    NativeAuthApiPigeonInternal.deepHash(value: scopes, hasher: &hasher)
    NativeAuthApiPigeonInternal.deepHash(value: expiresAtEpochMilliseconds, hasher: &hasher)
    NativeAuthApiPigeonInternal.deepHash(value: sentTo, hasher: &hasher)
    NativeAuthApiPigeonInternal.deepHash(value: codeLength, hasher: &hasher)
    NativeAuthApiPigeonInternal.deepHash(value: errorCode, hasher: &hasher)
    NativeAuthApiPigeonInternal.deepHash(value: errorMessage, hasher: &hasher)
  }

  public var description: String {
    return "NativeAuthResultMessage(type: \(String(describing: type)), operation: \(String(describing: operation)), continuationId: \(String(describing: continuationId)), username: \(String(describing: username)), idToken: \(String(describing: idToken)), accessToken: \(String(describing: accessToken)), scopes: \(String(describing: scopes)), expiresAtEpochMilliseconds: \(String(describing: expiresAtEpochMilliseconds)), sentTo: \(String(describing: sentTo)), codeLength: \(String(describing: codeLength)), errorCode: \(String(describing: errorCode)), errorMessage: \(String(describing: errorMessage)))"
  }
}

private class NativeAuthApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return NativePlatformMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return NativeAuthOperationMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return NativeAuthResultTypeMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      return NativeSdkStatusMessage.fromList(self.readValue() as! [Any?])
    case 133:
      return NativeAuthConfigurationMessage.fromList(self.readValue() as! [Any?])
    case 134:
      return NativeAuthSignInParametersMessage.fromList(self.readValue() as! [Any?])
    case 135:
      return NativeAuthAccessTokenParametersMessage.fromList(self.readValue() as! [Any?])
    case 136:
      return NativeAuthResultMessage.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class NativeAuthApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? NativePlatformMessage {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? NativeAuthOperationMessage {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? NativeAuthResultTypeMessage {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? NativeSdkStatusMessage {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? NativeAuthConfigurationMessage {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? NativeAuthSignInParametersMessage {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? NativeAuthAccessTokenParametersMessage {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? NativeAuthResultMessage {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class NativeAuthApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return NativeAuthApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return NativeAuthApiPigeonCodecWriter(data: data)
  }
}

class NativeAuthApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = NativeAuthApiPigeonCodec(readerWriter: NativeAuthApiPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol NativeAuthHostApi {
  func getNativeSdkStatus() throws -> NativeSdkStatusMessage
  func initialize(configuration: NativeAuthConfigurationMessage) async throws -> NativeAuthResultMessage
  func getCurrentAccount() async throws -> NativeAuthResultMessage
  func startSignIn(parameters: NativeAuthSignInParametersMessage) async throws -> NativeAuthResultMessage
  func startSignUp(username: String) async throws -> NativeAuthResultMessage
  func submitCode(continuationId: String, code: String) async throws -> NativeAuthResultMessage
  func submitPassword(continuationId: String, password: String) async throws -> NativeAuthResultMessage
  func resendCode(continuationId: String) async throws -> NativeAuthResultMessage
  func getAccessToken(parameters: NativeAuthAccessTokenParametersMessage) async throws -> NativeAuthResultMessage
  func signOut() async throws -> NativeAuthResultMessage
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class NativeAuthHostApiSetup {
  static var codec: FlutterStandardMessageCodec { NativeAuthApiPigeonCodec.shared }
  /// Sets up an instance of `NativeAuthHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: NativeAuthHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let getNativeSdkStatusChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.microsoft_entra_external_id.NativeAuthHostApi.getNativeSdkStatus\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getNativeSdkStatusChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getNativeSdkStatus()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getNativeSdkStatusChannel.setMessageHandler(nil)
    }
    let initializeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.microsoft_entra_external_id.NativeAuthHostApi.initialize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configurationArg = args[0] as! NativeAuthConfigurationMessage
        Task { @MainActor in
          do {
            let result = try await api.initialize(configuration: configurationArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      initializeChannel.setMessageHandler(nil)
    }
    let getCurrentAccountChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.microsoft_entra_external_id.NativeAuthHostApi.getCurrentAccount\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getCurrentAccountChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            let result = try await api.getCurrentAccount()
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      getCurrentAccountChannel.setMessageHandler(nil)
    }
    let startSignInChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.microsoft_entra_external_id.NativeAuthHostApi.startSignIn\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startSignInChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let parametersArg = args[0] as! NativeAuthSignInParametersMessage
        Task { @MainActor in
          do {
            let result = try await api.startSignIn(parameters: parametersArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      startSignInChannel.setMessageHandler(nil)
    }
    let startSignUpChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.microsoft_entra_external_id.NativeAuthHostApi.startSignUp\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startSignUpChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let usernameArg = args[0] as! String
        Task { @MainActor in
          do {
            let result = try await api.startSignUp(username: usernameArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      startSignUpChannel.setMessageHandler(nil)
    }
    let submitCodeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.microsoft_entra_external_id.NativeAuthHostApi.submitCode\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      submitCodeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let continuationIdArg = args[0] as! String
        let codeArg = args[1] as! String
        Task { @MainActor in
          do {
            let result = try await api.submitCode(continuationId: continuationIdArg, code: codeArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      submitCodeChannel.setMessageHandler(nil)
    }
    let submitPasswordChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.microsoft_entra_external_id.NativeAuthHostApi.submitPassword\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      submitPasswordChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let continuationIdArg = args[0] as! String
        let passwordArg = args[1] as! String
        Task { @MainActor in
          do {
            let result = try await api.submitPassword(continuationId: continuationIdArg, password: passwordArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      submitPasswordChannel.setMessageHandler(nil)
    }
    let resendCodeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.microsoft_entra_external_id.NativeAuthHostApi.resendCode\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      resendCodeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let continuationIdArg = args[0] as! String
        Task { @MainActor in
          do {
            let result = try await api.resendCode(continuationId: continuationIdArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      resendCodeChannel.setMessageHandler(nil)
    }
    let getAccessTokenChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.microsoft_entra_external_id.NativeAuthHostApi.getAccessToken\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getAccessTokenChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let parametersArg = args[0] as! NativeAuthAccessTokenParametersMessage
        Task { @MainActor in
          do {
            let result = try await api.getAccessToken(parameters: parametersArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      getAccessTokenChannel.setMessageHandler(nil)
    }
    let signOutChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.microsoft_entra_external_id.NativeAuthHostApi.signOut\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      signOutChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            let result = try await api.signOut()
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      signOutChannel.setMessageHandler(nil)
    }
  }
}
